#!/bin/bash

#
# This file is part of ProductionMemcheck.
#
# Copyright Jan Horak 2023
#
# Based on mutrace shell script: Copyright 2009 Lennart Poettering
#

# Default is to start memcheck from process beginning.
export PRODUCTION_MEMCHECK_ENABLED="y"

CURDIR=`realpath "$0"`
CURDIR=`dirname "$CURDIR"`

if ! TEMP=`getopt -o +h,v,d:,n,s:,S:,c: --long help,verbose,depth:,no-start,start:,start-allocations:,start-deallocations:,stop:,stop-allocations:,stop-deallocations:,collect: -n production_memcheck -- "$@"` ; then
    exit 1
fi

eval set -- "$TEMP"

while : ; do
  case $1 in
    -h|--help)
      cat <<EOF
production_memcheck 0.1

Usage: production_memcheck [OPTIONS...] APPLICATION [ARGUMENTS...]

COMMANDS:
  -d, --depth arg (=10)           Sets used backtrace depth.
  -h, --help                      Show this help.
  -n, --no-start                  Do not process allocations nor deallocations until start is used.
  -s, --start                     Start processing allocations and deallocations.
      --start-allocations         Start processing allocations only.
      --start-deallocations       Start processing deallocations only.
  -S, --stop                      Stop processing allocations and deallocations.
      --stop-allocations          Stop processing allocations only.
      --stop-deallocations        Stop processing deallocations only.
  -c, --collect                   Collect saved (de)allocations and write stats to output file.
  -v, --verbose                   Enable logging.
EOF
      exit 0
      ;;

    -v|--verbose)
      shift
      export PRODUCTION_MEMCHECK_VERBOSE="y"
      ;;

    -d|--depth)
      shift
      export PRODUCTION_MEMCHECK_DEPTH="$1"
      shift
      ;;

    -n|--no-start)
      shift
      unset PRODUCTION_MEMCHECK_ENABLED
      ;;

    -s|--start)
      shift
      ${CURDIR}/production_memcheck_tool $1 start
      shift
      exit
      ;;

    --start-allocations)
      shift
      ${CURDIR}/production_memcheck_tool $1 start allocations
      shift
      exit
      ;;

    --start-deallocations)
      shift
      ${CURDIR}/production_memcheck_tool $1 start deallocations
      shift
      exit
      ;;

    -S|--stop)
      shift
      ${CURDIR}/production_memcheck_tool $1 stop
      shift
      exit
      ;;

    --stop-allocations)
      shift
      ${CURDIR}/production_memcheck_tool $1 stop allocations
      shift
      exit
      ;;

    --stop-deallocations)
      shift
      ${CURDIR}/production_memcheck_tool $1 stop deallocations
      shift
      exit
      ;;

    -c|--collect)
      shift
      ${CURDIR}/production_memcheck_tool $1 collect
      shift
      exit
      ;;

    --)
      shift
      break
      ;;

    *)
      echo "Parsing failed! '$1'" >&2
      exit 1
      ;;

  esac

done

shift $(($OPTIND-1))

if [ x"$1" = x ] ; then
  echo "Please specify an application to use!" >&2
  exit 1
fi

if [ x"$LD_PRELOAD" = x ] ; then
  export LD_PRELOAD="$CURDIR/libproduction_memcheck.so"
else
  export LD_PRELOAD="$LD_PRELOAD:$CURDIR/libproduction_memcheck.so"
fi

#export GLIBCPP_FORCE_NEW="1"
#export GLIBCXX_FORCE_NEW="1"

# Default Debian debug libraries.
#DBGPATH=/usr/lib/debug

#export RUNNING_ON_VALGRIND="1"

exec "$@"
