#!/bin/bash

#
# This file is part of ProductionMemcheck.
#
# Copyright Jan Horak 2023
#
# Based on mutrace shell script: Copyright 2009 Lennart Poettering
#

if ! TEMP=`getopt -o +h,v --long help,verbose -n production_memcheck -- "$@"` ; then
    exit 1
fi

eval set -- "$TEMP"

while : ; do
  case $1 in
    -h|--help)
      cat <<EOF
production_memcheck 0.1

Usage: production_memcheck [OPTIONS...] APPLICATION [ARGUMENTS...]

COMMANDS:
  -h, --help                      Show this help
EOF
      exit 0
      ;;

    -v|--verbose)
      shift
      export PRODUCTION_MEMCHECK_VERBOSE="y"
      ;;

    --)
      shift
      break
      ;;

    *)
      echo "Parsing failed! '$1'" >&2
      exit 1
      ;;

  esac

done

shift $(($OPTIND-1))

if [ x"$1" = x ] ; then
  echo "Please specify an application to use!" >&2
  exit 1
fi

if [ x"$LD_PRELOAD" = x ] ; then
  export LD_PRELOAD="$(dirname $0)/libproduction_memcheck.so"
else
  export LD_PRELOAD="$LD_PRELOAD:$(dirname $0)/libproduction_memcheck.so"
fi

export PRODUCTION_MEMCHECK_ENABLED="y"

exec "$@"
